### ISSUE TITLE
How to include in Xaringan slides

### ISSUE THREAD

**Issue by Robinlovelace** [feddelegrand7/fabricerin#3]
The readme states that 

> you can also use it within your xaringan slides

Awesome, but how? I looked at the original tweet and an associated issue: https://github.com/yihui/xaringan/issues/204

Thanks for a fantastic package. FYI, it works great with a Wacom drawing tablet and pen :pen: :tada:

**Comment by Robinlovelace** [comment]
Reproducible example, create a file called test.Rmd and paste the following, then run:

```
---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, PBC"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
# runtime: shiny
---

background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/be/Sharingan_triple.svg)

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

???

Image credit: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Sharingan_triple.svg)

---
## Illustration

```{r, echo=FALSE}
library(shiny)
library(fabricerin)


ui <- fluidPage(
  
  
  fabric_drawing(cid = "canvas123")

)

server <- function(input, output){}

shinyApp(ui, server)
```

```
